### ISSUE TITLE
Req: Open up the Wiki for submitting examples?

### ISSUE THREAD

**Issue by philipsd6** [haochi/personalcapital#16]
@haochi, if the Wiki were available, I could submit a few examples I've build for myself, including how to process results into a Pandas DataFrame. WDYT?

**Comment by jcguu95** [comment]
That would be awesome! It connects with my PC account, but it only gets my net worth and number of transaction for the past three months. Ideally, I would like to scrape all data (hopefully all transactions csv file). Not sure if it's currently possible.

**Comment by philipsd6** [comment]
Anything should be possible, given that this is the same API the PersonalCapital website uses -- if you can do it there, you can do it here.

**Comment by jcguu95** [comment]
I tried to search for Personal Capital's API documentation, but there seemed to be none. I also asked customer service, and they responded me that they don't support API currently. How did you manage to know the key? And before PC document their API, is it really possible to get all data automatically?

**Comment by haochi** [comment]
Done
