### ISSUE TITLE
Not necessarily an issue...more just general question

### ISSUE THREAD

**Issue by bpassini12** [haochi/personalcapital#23]
How do you know what other fetch commands there are besides '/newaccount/getAccounts'?

I also found that '/invest/getHoldings' works too, but I forget how I even figured that out.

I don't know a ton about APIs. I'd appreciate any help.

-Brett

**Comment by ulygit** [comment]
You can find what commands are available by logging into your Personal Capital account via a web browser and navigating around the site while observing the network requests that are sent from your browser (and the responses that come back). If you enable the "developer" tools in your browser and play around with the features, you'll get a screen detailing the network traffic.

**Comment by bpassini12** [comment]
@ulygit I already see what you mean. Thank you very much, very helpful!
