### ISSUE TITLE
GET_ACCOUNT_DATA error

### ISSUE THREAD

**Issue by isailk1** [haochi/personalcapital#7]
I am running main.py from Windows, seem to get passed two-factor authentication.   
Getting response below:
**{"spHeader":{"SP_HEADER_VERSION":-1,"success":false,"userGuid":"c87d2e4d4b0f4fce908042c406c398a2","authLevel":"USER_IDENTIFIED","errors":[{"code":200,"details":{"actionType":"GET_ACCOUNT_DATA"},"message":"Authorization required."},{"code":201,"message":"Session not authenticated."}],"username":"xxx@yyy.com","status":"ACTIVE"}}**

Please advise.

**Comment by haochi** [comment]
Looks like you didn't authenticate successfully from the error message. There's no API doc available from Personal Capital so it's all guess work really.

**Comment by haochi** [comment]
@iantrich Once you load a saved session you shouldn't need to authenticate any more.

**Comment by iantrich** [comment]
@haochi Have you tried the `main.py` from the project recently? I don't think I'm missing anything, but running that a 2nd time I get the following

```
Traceback (most recent call last):
  File "pc.py", line 87, in <module>
    main()
  File "pc.py", line 80, in main
    accounts = accounts_response.json()['spData']
KeyError: 'spData'
```

which makes me believe that the `session.json` is not being loaded properly. I admittedly know very little about sessions/cookies, but was hoping that my PR to bump the `requests` module might help.

**Comment by iantrich** [comment]
@haochi also, if you're curious, this is the project I'm currently working on with your module: https://github.com/custom-components/sensor.personalcapital

It a custom-component for [Home Assistant](https://www.home-assistant.io/). It currently works great, but I have to reauthenticate every restart and the session seems to expire within a day when trying to use it every 30 minutes to keep it alive.

**Comment by iantrich** [comment]
I had a friend try `main.py` and he had no issues, so it must be something wrong on my end.

**Comment by iantrich** [comment]
@haochi figured it out! I had my account set to always require a 4 digit code. All this trouble has been my own doing 🤣 Thanks for the assistance and the module. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iantrich** [comment]
Noted. Thanks

**Comment by 4G-Gregg** [comment]
@iantrich I'm encountering the same issue, how did you turn that functionality off in your account?

**Comment by iantrich** [comment]
@4G-Gregg it's in the account settings
